[package]
name = "tiler"
version = "0.1.0"
edition = "2021"

[dependencies]
json_comments = "0.2.2"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
svg = "0.18.0"
svg2pdf = "0.12.0"
